### PR TITLE
[wayc] Fix pointer focus when pointer hasn't moved

### LINKED ISSUE #5547: [wayc] Switching windows with keys not working correctly
### Issue description

With `follow_mouse_focus = True`

Open a couple of terminals side by side in Columns layout
`layout.left()` and `layout.right()` will switch between the two windows

Move the mouse
Now `layout.left()` and `layout.right()`fails to switch between the windows

### Version

wayc

### Backend

Wayland (experimental)

### Config

```python
follow_mouse_focus = True
```

### Logs

```text

```

### Required

- [x] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

### PR DESCRIPTION
**Pull request by richcarni**
If the pointer hasn't moved but windows have changed, we need a different focus behaviour than for cursor motion. Both on wayc and python sides

To this end I have removed a function to only update pointer without motion from `qw_cursor_process_motion()` so it can be called independently. And added a motion parameter to `core._focus_pointer()` to modify its behaviour

Added a check to only call `wlr_seat_pointer_notify_enter()` if the surface under the pointer has changed. Maybe get a small performance gain here

And some refactoring

Fixes #5547

### CODE REVIEW

File: libqtile/backend/wayland/qw/cursor.c [hunk 1]
```diff
@@ -19,6 +19,36 @@ void qw_cursor_destroy(struct qw_cursor *cursor) {
...
+    struct wlr_seat *seat = cursor->server->seat;
+
+    struct wlr_surface *tmp_surface = NULL;
+    double tmp_sx = 0.0, tmp_sy = 0.0;
+
+    cursor->view = qw_server_view_at(cursor->server, cursor->cursor->x, cursor->cursor->y,
+                                     &tmp_surface, &tmp_sx, &tmp_sy);
+
+    // Reset cursor if there's no view and we're not dragging
+    if ((!cursor->view || !tmp_surface) && cursor->server->seat->drag == NULL) {
```
Comment (richcarni) [inline libqtile/backend/wayland/qw/cursor.c:33]: Can someone double check this logic with me? (I haven't changed it)

If either view or surface is NULL and drag is NULL then reset cursor and don't notify enter - OK

But what if surface is NULL and drag is not NULL? It's going to try and notify enter with a NULL surface

Am I interpreting this correctly

Comment (elParaguayo) [reply libqtile/backend/wayland/qw/cursor.c:33]: I did it like this:
```diff
diff --git a/libqtile/backend/wayland/qw/cursor.c b/libqtile/backend/wayland/qw/cursor.c
index 88d20260..00a1de55 100644
--- a/libqtile/backend/wayland/qw/cursor.c
+++ b/libqtile/backend/wayland/qw/cursor.c
@@ -63,8 +63,10 @@ static void qw_cursor_process_motion(struct qw_cursor *cursor, uint32_t time) {
                                 (int)cursor->cursor->y);

     // Reset cursor if there's no view and we're not dragging
-    if ((!view || !surface) && cursor->server->seat->drag == NULL) {
-        wlr_cursor_set_xcursor(cursor->cursor, cursor->mgr, "default");
+    if (surface != NULL) {
+        if (cursor->server->seat->drag == NULL) {
+            wlr_cursor_set_xcursor(cursor->cursor, cursor->mgr, "default");
+        }
         wlr_seat_pointer_clear_focus(seat);
         return;
     }
```

However, I've tested your code and I also don't get the crash when dragging.

**Comment by Gurjaka** [comment]
fixes: https://github.com/qtile/qtile/issues/5561
