### PR TITLE
wayland: Add xcursor configuration

### LINKED ISSUE #5706: [wayc] `wl_xcursor_size = 48` doesn't work.
### Issue description

How to reproduce: add  `wl_xcursor_size = 48` to config. 

Nothing happens, the cursor remains tiny above qtile elements such as the bar or an empty group. Separate compositor independent theming works in individual apps. 

On the same computer `seat * xcursor_theme Adwaita 48
` works in Sway.

### Version

0.34.1.dev21+g6a8a263c6

### Backend

Wayland (experimental)

### Config

```python
from libqtile import hook, layout, bar, widget
from libqtile.config import Screen, Group, Key
from libqtile import qtile
from libqtile.lazy import lazy 
from libqtile.backend.wayland import InputConfig

wl_xcursor_theme = "Adwaita"
wl_xcursor_size = 48

wl_input_rules = {
    "*": InputConfig(
        left_handed=False,
        pointer_accel=False,
        accel_profile="flat",
    ),

    "type:keyboard": InputConfig(
        kb_layout="hu",
        kb_variant="102_qwerty_comma_nodead",
    ),
}

mod = "mod4"

keys = [
    Key([mod], "h", lazy.layout.left()),
    Key([mod], "l", lazy.layout.right()),
    Key([mod], "j", lazy.layout.down()),
    Key([mod], "k", lazy.layout.up()),
    Key([mod], "Return", lazy.spawn("xterm")),
    Key([mod], "q", lazy.window.kill()),
    Key([mod, "control"], "r", lazy.restart()),
    # --- New Screenshot Key Binding ---
    Key([], "Print", lazy.spawn('grim -g "0,0 1920x1080"')),
]

groups = [Group(i) for i in "asdfuiop"]

for i in groups:
    keys.append(Key([mod], i.name, lazy.group[i.name].toscreen()))
    keys.append(Key([mod, "shift"], i.name, lazy.window.togroup(i.name)))

layouts = [
    layout.MonadTall(),
    layout.Max(),
]

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Clock(format='%Y-%m-%d %H:%M:%S'),
            ],
            24,
        ),
    ),
]

@hook.subscribe.startup_once
def autostart():
    qtile.cmd_spawn("/home/Q/.config/qtile/autostart.sh")
```

### Logs

```text
no relevant logs
```

### Required

- [x] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

### PR DESCRIPTION
**Pull request by richcarni**
Set xcursor size and theme from config variables: wl_xcursor_size and
wl_xcursor_theme

Added a general function for reading parameters from qtile config,
for this purpose

Largely following sway's implementation

Fixes #5706

Tested (as best I can):
- [x] Setting base cursor size
- [x] Cursor scales automatically with output scale
- [x] Size updates when changed in config and config reloaded
- [x] Setting cursor theme

### CODE REVIEW

File: libqtile/backend/wayland/qw/cursor.c [hunk 1]
```diff
@@ -569,3 +569,78 @@ void qw_cursor_pointer_constraint_new(struct qw_cursor *cursor,
...
+void qw_cursor_configure_xcursor(struct qw_cursor *cursor) {
+    unsigned cursor_size = 24;
+    const char *cursor_theme = NULL; // Defaults prob not necessary here?
+
+    struct qw_server *server = cursor->server;
+    struct qw_qtile_config *config = server->get_qtile_config_cb(server->cb_data);
+    cursor_size = config->wl_xcursor_size;
+    cursor_theme = config->wl_xcursor_theme;
+
+    wlr_log(WLR_ERROR, "config cursor size %i", config->wl_xcursor_size);
```
Comment (elParaguayo) [inline libqtile/backend/wayland/qw/cursor.c]: Debugging statement?

Comment (richcarni) [reply libqtile/backend/wayland/qw/cursor.c]: Yup 😳

**Comment by richcarni** [comment]
Bit more complicated than I thought it would be

It basically works (need to add update when config reloaded but that's not hard)

but behaviour is weird with screen scaling. Sometimes it changes size with scale, sometimes it doesn't. Do cursor images only come in discrete sizes or something and it just chooses the nearest?

This might be helpful - I'm still parsing it
https://blogs.kde.org/2024/10/09/cursor-size-problems-in-wayland-explained/

**Comment by richcarni** [comment]
@elParaguayo since you've already seen this one, would you mind casting your eyes over it again (and approve or merge). Thanks!

File: libqtile/backend/wayland/qw/cursor.c [hunk 2]
```diff
@@ -569,3 +569,72 @@ void qw_cursor_pointer_constraint_new(struct qw_cursor *cursor,
         qw_cursor_constrain_cursor(cursor, constraint);
     }
 }
+
+static bool xcursor_manager_is_named(const struct wlr_xcursor_manager *manager, const char *name) {
+    return (!manager->name && !name) || (name && manager->name && strcmp(name, manager->name) == 0);
```
Comment (elParaguayo) [inline libqtile/backend/wayland/qw/cursor.c]: Are these checking for `NULL`?

File: libqtile/backend/wayland/qw/cursor.c [hunk 3]
```diff
@@ -569,3 +569,72 @@ void qw_cursor_pointer_constraint_new(struct qw_cursor *cursor,
...
+    char cursor_size_fmt[16];
+    snprintf(cursor_size_fmt, sizeof(cursor_size_fmt), "%u", cursor_size);
+    setenv("XCURSOR_SIZE", cursor_size_fmt, 1);
+    if (cursor_theme != NULL) {
+        setenv("XCURSOR_THEME", cursor_theme, 1);
+    }
+
+#if WLR_HAS_XWAYLAND
+    if (server->xwayland &&
+        (!cursor->xwayland_mgr || !xcursor_manager_is_named(cursor->xwayland_mgr, cursor_theme) ||
```
Comment (elParaguayo) [inline libqtile/backend/wayland/qw/cursor.c]: Another `NULL` check?

File: libqtile/backend/wayland/qw/cursor.c [hunk 4]
```diff
@@ -569,3 +569,72 @@ void qw_cursor_pointer_constraint_new(struct qw_cursor *cursor,
...
+         cursor->xwayland_mgr->size != cursor_size)) {
+
+        wlr_xcursor_manager_destroy(cursor->xwayland_mgr);
+
+        cursor->xwayland_mgr = wlr_xcursor_manager_create(cursor_theme, cursor_size);
+        if (!cursor->mgr) {
```
Comment (elParaguayo) [inline libqtile/backend/wayland/qw/cursor.c]: And another...

File: libqtile/backend/wayland/qw/cursor.c [hunk 5]
```diff
@@ -569,3 +569,72 @@ void qw_cursor_pointer_constraint_new(struct qw_cursor *cursor,
...
+            struct wlr_xcursor_image *image = xcursor->images[0];
+            wlr_xwayland_set_cursor(server->xwayland, image->buffer, image->width * 4, image->width,
+                                    image->height, image->hotspot_x, image->hotspot_y);
+        }
+    }
+#endif
+
+    /* Create xcursor manager if we don't have one already, or if the
+     * theme has changed */
+    if (cursor->mgr || !xcursor_manager_is_named(cursor->mgr, cursor_theme) ||
```
Comment (elParaguayo) [inline libqtile/backend/wayland/qw/cursor.c]: You know...

File: libqtile/backend/wayland/qw/cursor.c [hunk 6]
```diff
@@ -569,3 +569,72 @@ void qw_cursor_pointer_constraint_new(struct qw_cursor *cursor,
...
+        cursor->mgr->size != cursor_size) {
+        wlr_xcursor_manager_destroy(cursor->mgr);
+        cursor->mgr = wlr_xcursor_manager_create(cursor_theme, cursor_size);
+        if (!cursor->mgr) {
```
Comment (elParaguayo) [inline libqtile/backend/wayland/qw/cursor.c]: Running out of different ways to say it...

**Comment by richcarni** [comment]
Thanks for pointing those out. Next time feel free to stop after 2 and tell me to find the rest myself!!
