### PR TITLE
[wayland] Implement pointer constraints

### LINKED ISSUE #5668: Wayland: Erratic camera rotation and failure to confine cursor during input capture
When an XWayland application attempts to lock (force grab) the mouse cursor for camera control (e.g., FPS/TPS games), the camera exhibits erratic behavior, often spinning uncontrollably.

Additionally, the cursor is not explicitly confined to the window geometry, allowing it to drift out of focus or hit screen edges.

**Reproduction Steps**
1. Launch a Steam game running via XWayland (Tested: *Elden Ring, CS2, Batman Arkham Knight, Doom Eternal*).
2. Enter a state requiring mouse look/cursor lock (gameplay or viewport mode).
3. Move the mouse in any direction.

**Expected Behavior**
* **Cursor:** Should be hidden and confined to the window center (or locked via relative pointer protocols).
* **Camera:** Movement should map 1:1 with mouse deltas without acceleration spikes or spinning.

**Actual Behavior**
* **Camera:** View spins rapidly/erratically, likely interpreting cursor re-centering as input delta.
* **Cursor:** Pointer remains visible (or ghosts) and ignores window boundaries, exiting the application context.

**Visual Proof**
* **Issue demonstration (Captured by OBS):** [Link to video 1](https://files.catbox.moe/yplyzv.mp4)
* **Issue demonstration (Capture by phone)** [Link to video 2](https://github.com/user-attachments/assets/19268589-250a-40ef-b9e1-03546f35e57c)

**Environment**
* **OS:** `NixOS 25.11 (Xantusia) x86_64`
* **Backend:** `Wayland`
* **Qtile Version:** `0.34.0+4604d3e.flake`
* **GPU/Driver:** `Radeon Rx7800xt/Mesa 25.3.0`

---

### Regression / Fix Attempt
@richcarni suggested testing **PR #5635** to address this.
**Result:** The PR changes behavior but introduces new regressions:
1.  **Forced Acceleration:** Mouse acceleration is present despite being disabled in the config.
2.  **Input Failure on Click:** Standard movement works better, but `Click + Drag` (or move) triggers the old erratic behavior immediately.

**[Footage](https://files.catbox.moe/pzkx6g.mp4) of PR #5635 behavior:**

### PR DESCRIPTION
**Pull request by richcarni**
Pointer can be locked or confined to a region. Relative motion events are emitted when locked

Closely follows how this is implemented in sway

Limited testing with https://stackoverflow.com/a/78838558

Additional real world testing with the following games working correctly:
- Helldivers 2
- Satisfactory  
- RV There Yet
- System Shock (2023)
- Elden Ring
- Doom Eternal
- Counter Strike 2
- Batman Arkham Knight

Fixes #5668

### CODE REVIEW

**Comment by richcarni** [comment]
Can't help but feel it's getting difficult to reason about what is going on around motion handling - feedback appreciated!
UPDATE: did some refactoring around this - I think it's an improvement

Also finding it difficult to test this one thoroughly. Maybe best we can do it put it out there and respond to users' issues?

**Comment by richcarni** [comment]
@jwijenbergh @elParaguayo ready for review/merge (the fail is just readthedocs)

**Comment by elParaguayo** [comment]
I'm also struggling to test this one. chatgpt has written a client implementation which requests and gets confirmation of a lock. However, I can still move mouse freely but button presses are blocked. This could all just be an error with chatgpt's code though!

**Comment by jwijenbergh** [comment]
Why not just test with https://gitlab.freedesktop.org/wlroots/wlr-clients/-/blob/master/pointer-constraints.c

**Comment by elParaguayo** [comment]
Ah! That's where they moved their example code (it was part of the wlroots repo in earlier versions).

I have run this script already and didn't see any constraints being applied but that could be because I was running from wephyr.

**Comment by richcarni** [comment]
Let me test with the same script and report back
...
Well, for me, in a vm, this program just segfaulted

Surely there is a real world application that uses pointer constraints!

**Comment by elParaguayo** [comment]
In my idle PR, I've got a helper function to retrieve a view from a surface.

**Comment by richcarni** [comment]
> In my idle PR, I've got a helper function to retrieve a view from a surface.

Thanks! I'll be sure to use it

This PR is dragging on. Difficult to debug when I don't have the game(s) people are having issues with. I followed sway pretty closely so you'd think it would be hard to mess up... somehow I appear to have found a way

File: libqtile/backend/wayland/qw/util.c [hunk 1]
```diff
@@ -122,3 +122,48 @@ bool qw_surfaces_on_same_output(struct wlr_surface *surface_a, struct wlr_surfac
     }
     return false;
 }
+
+struct qw_view *qw_view_from_wlr_surface(struct wlr_surface *surface, bool *is_layer_surface, bool *is_session_lock_surface) {
+    is_layer_surface = false;
+    is_session_lock_surface = false;
```
Comment (elParaguayo) [inline libqtile/backend/wayland/qw/util.c]:
```suggestion
    *is_layer_surface = false;
    *is_session_lock_surface = false;
```
I think we need this as we're receiving pointers to those values.

**Comment by elParaguayo** [comment]
@richcarni sounds like we're ready to merge this. Do you agree?

**Comment by richcarni** [comment]
> @richcarni sounds like we're ready to merge this. Do you agree?

Yeah, I think so!
